name: chat_repository
description: Dart package which manages the comment.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  # Firebase

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  cloud_firestore: ^4.9.0
  uuid: ^4.3.3
  intl: ^0.19.0
  firebase_storage: ^11.6.5


  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
