name: post_repository
description: Dart package which manages the user.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  # Firebase

  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.10
  equatable: ^2.0.5
  cloud_firestore: ^4.9.0
  uuid: ^4.3.3
  firebase_storage: ^11.6.5
  http: ^1.2.0


  user_repository:
    path: ../user_repository
  comment_repository:
    path: ../comment_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
